### ISSUE TITLE
Opportunity Gatekeeper Page Does Not Match Design

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#13]
http://104.236.242.180/html/products-opportunity-gatekeeper.html this is correct design for http://104.236.242.180/full-wp/products/opportunity-gatekeeper/

**Comment by PolitoTech** [comment]
Looks like in The Product Sub-Pages you have the row Why Full Circle CRM? where you should have the Built Natively on the Salesforce1... row

**Comment by PolitoTech** [comment]
This issue is also on http://104.236.242.180/full-wp/products/easy-campaign-member-status/ see http://104.236.242.180/html/products-easy-member.html for correct design.

**Comment by kossa** [comment]
Please How many different page we have ?
Very strange, because I made each section -> one page

**Comment by PolitoTech** [comment]
We did not notice that under Products there are three different page templates. The only difference between 2 of them is one row in design as said above. In this case you have the Products Template, A second template for Response Management and Campaign Influence, and a Third Template for Opportunity Gatekeeper and Easy Member.

**Comment by PolitoTech** [comment]
Still not correct wrong native to salefroce add on Opportunity Gatekeeper and Easy Member.

SEE http://104.236.242.180/html/products-opportunity-gatekeeper.html for correct one

**Comment by kossa** [comment]
Where is the problem ?

**Comment by PolitoTech** [comment]
There are 2 different "Built Natively on..." sections in the design.
1. http://104.236.242.180/html/
2. http://104.236.242.180/html/products-opportunity-gatekeeper.html

Please note they are not the same design. You currently put number 1 on http://104.236.242.180/full-wp/products/opportunity-gatekeeper/ and http://104.236.242.180/full-wp/products/easy-campaign-member-status/. These two pages should have #2 from above. This is correct in HTML version.
