### ISSUE TITLE
Bullet List Style is not correct

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#16]
The Bullet list style needs to include multi line indent to match same as first line. need all bullets to align properly no matter what size the screen is or how many lines of text.  bullet point indentation on lines 2 and on.

**Comment by kossa** [comment]
Please send me link, and screenshot I did not understand :p

**Comment by PolitoTech** [comment]
![2015-06-19_14-51-23](https://cloud.githubusercontent.com/assets/4174069/8261516/336e1058-1699-11e5-83d8-91ebfeb5dcb0.png)

**Comment by PolitoTech** [comment]
Missed the pricing page for this update. http://104.236.242.180/full-wp/pricing/

**Comment by kossa** [comment]
Done
