### ISSUE TITLE
Products Page Sub-Headings Not correct Color or Size

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#18]
subheads under Full Circle Response Management and Full Circle Campaign Influence should be smaller and text should be grey (per the PSD). Currently you can see the text OUR FLAGSHIP MARKETING PERFORMANCE MANAGEMENT PRODUCT is in orange in larger, also to much spacing after Heading.

SEE PSD = https://drive.google.com/file/d/0B_EVFVP7a8RDNWZjcjBPc0RfYzA/view?usp=sharing

**Comment by kossa** [comment]
I'm angry, we said before all css are done, just including in Wordpress, right ?

**Comment by PolitoTech** [comment]
Do not be angry...It is correct here -->http://104.236.242.180/html/products.html. Just in WordPress is wrong.

**Comment by kossa** [comment]
So I'm angry because you did was not clear hhhhhhhhhh
