### ISSUE TITLE
Response Management Sub Pages Main Icon and Heading does not Match Design

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#19]
On any of the Response Management Sub-Pages Like http://104.236.242.180/full-wp/products/response-management/marketing-to-sales-handoff/ you can see that the first Headline with the icon on the left does not match design. The icon should be closer to heading and then a line underneath.

SEE https://drive.google.com/drive/folders/0B_EVFVP7a8RDfmNDcTA5VDZCelNFQUdlZkM4RXpEc0lRYWI4bS1kYW55TG1BNFZrcEZ6bjA

**Comment by kossa** [comment]
Fixed
