### ISSUE TITLE
Customer Page Quote " Not showing under featured and 0 under logos

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#22]
1. The quote under feature is missing a  quote mark " at the beginning
2. The logos no have 0 under them. That should be removed
3. Background image behinds Featured Quotes

SEE http://104.236.242.180/full-wp/customers/
Correct = http://104.236.242.180/html/customers.html

**Comment by kossa** [comment]
Not clear

**Comment by PolitoTech** [comment]
![2015-06-19_14-51-23](https://cloud.githubusercontent.com/assets/4174069/8260658/20c8bfa8-1693-11e5-88eb-9628fa438b56.png)

**Comment by PolitoTech** [comment]
![2015-06-19_15-46-23](https://cloud.githubusercontent.com/assets/4174069/8261708/9310f8a8-169a-11e5-9a3f-58335698d33d.png)
