### ISSUE TITLE
Change Footer Design

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#24]
![footer options](https://cloud.githubusercontent.com/assets/4174069/8271836/e0d4afb6-17f9-11e5-8981-675009963519.png)

**Comment by kossa** [comment]
Need the PSD

**Comment by PolitoTech** [comment]
Before we get PSD for the launch the client asked the following:

To get it ready for launch (not including the newer stuff we talked about) I need the following:
1. Delete footer column 2 (Services)
2. Put in the 2015 copyright date on the bottom of the footer (like what we have on our current site - http://fullcirclecrm.com/)
3. Put in the contact / Privacy & Terms horizontally at the bottom of our current footer - http://fullcirclecrm.com/

For 2/3 here is the code from the old site - not sure if you can just paste it into the .php file:

<div class="copyright">
                        &copy;<?php echo date('Y'); ?> Copyright Full Circle CRM <span></span> <a href="<?php echo get_home_url(null, 'contact-us'); ?>">Contact</a> | <a href="<?php echo get_home_url(null, 'privacy'); ?>">Privacy <span class="amp"> &amp; </span> Terms</a>
                    </div>

```
            </div>
```
