### ISSUE TITLE
Pricing Page does not match Design

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#30]
$$ amounts for Opportunity Gatekeeper and Easy Campaign Member Status should be below the text - not next to it

See --> http://104.236.242.180/html/pricing.html

**Comment by PolitoTech** [comment]
![2015-06-21_11-51-12](https://cloud.githubusercontent.com/assets/4174069/8272334/02639ad6-180c-11e5-9bd2-a8006b7b929d.png)

**Comment by kossa** [comment]
Fixed: http://104.236.242.180/full-wp/pricing/
