### ISSUE TITLE
Quote Name and Title should be on to lines

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#39]
![2015-06-25_11-33-51](https://cloud.githubusercontent.com/assets/4174069/8358520/9cd350b4-1b2e-11e5-956a-d1fa4b26f901.png)

**Comment by kossa** [comment]
For each quote you should use small like : http://i.imgur.com/YboXWYg.png
Check : http://104.236.242.180/full-wp/products/campaign-influence/
