### ISSUE TITLE
How to add screenshots in Lightbox links

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#45]
How do you put in the see the screenshot images in pages detailed in email

**Comment by PolitoTech** [comment]
Also how do I add See the Screen shot links on other pages

**Comment by kossa** [comment]
Where is the link ? always include link :p

**Comment by PolitoTech** [comment]
http://104.236.242.180/full-wp/products/campaign-influence/ on this page how do I updated the see the screenshot links with the correct images for light box. Second http://104.236.242.180/full-wp/products/campaign-influence/ if we wanted to add see the screenshot to this page and have ligjtbix open on click. How is that done?

**Comment by kossa** [comment]
Ahh I see,
If you edit the page you'll see : 
`<a class="learn-more" href="#" data-toggle="modal" data-target="#model-01">See the screenshot</a>`
this is for the link
for the image easy at the bottom you'll see :

```
<div id="model-01" class="modal fade img-popup" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body"><img src="http://104.236.242.180/full-wp/wp-content/uploads/2015/05/img-21.png" alt="" /></div>
        </div>
    </div>
</div>
```

**Comment by kossa** [comment]
See this : http://i.imgur.com/mpB3oWm.png
