### ISSUE TITLE
img-35.png did not updated when new one was uploaded

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#56]
The img-35.png did not update to new image. Current - http://104.236.242.180/full-wp/wp-content/uploads/2015/05/img-35.png

Upload the following:

![img-35](https://cloud.githubusercontent.com/assets/4174069/8504138/ae39c448-2199-11e5-95d7-52dc4e602ea9.png)

**Comment by kossa** [comment]
if an images not in the theme so you can use FTP,
I' uploaded it ;)
