### ISSUE TITLE
Data driven marketers content wrong in client carousel

### ISSUE THREAD

**Issue by PolitoTech** [kossa/full-wp#6]
The heading that starts Data driven marketers in the home page above the clients carousel should be Data-driven marketers. Also how do you edit that info?

**Comment by kossa** [comment]
Here you can change it : https://github.com/kossa/full-wp/commit/85871431cc9f14e1dc3cba48303f45c2e1225509#diff-3a7207efd19bc0d4ac6f0fe17c10e849
